spring.application.name=app-viajes
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicios_usuarios
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug